### ISSUE TITLE
AutoDetection of attachments layer by layer

### ISSUE THREAD

**Issue by SCMGeocom** [Esri/attachment-viewer#12]
Please allow auto detection of attachments.

I have several layers in the map. Each (or almost each) have attachments. 
Allow the user to identify the object in the map and show the attachment(s).

![image](https://user-images.githubusercontent.com/47363379/60394370-6f00e100-9b23-11e9-84a9-fef852019721.png)

**Comment by rslibed** [comment]
In the October 2019 release we have provided various enhancements, one of them being multiple layer support. 
If a web map contains multiple layers with attachments, the application will provide a dropdown where the end-user can specify which layer's attachments to view.

Attachment focused layout: 
![attachment](https://user-images.githubusercontent.com/29421380/66067073-afe00b80-e4ff-11e9-9015-2e8950b75283.png)

Map focused layout: 
![map](https://user-images.githubusercontent.com/29421380/66067137-d1d98e00-e4ff-11e9-8c42-63a33e0fc96b.png)

**Comment by SCMGeocom** [comment]
Works very well now, thanks!
