### ISSUE TITLE
How to configure for Portal ?

### ISSUE THREAD

**Issue by mayur9785** [Esri/attachment-viewer#22]
Hi,
Does this attachment-viewer support Portal for ArcGIS ?
I have Survey123 app enabled with multiple photos in my Portal.
How do I configure this app for Portal for ArcGIS ?

Thanks,
Mayur

**Comment by rslibed** [comment]
Attachment Viewer should now be supported in Portal for ArcGIS

**Comment by rslibed** [comment]
Closing issue now that Attachment Viewer is supported in Portal for ArcGIS. Feel free to re-open if needed.
