### ISSUE TITLE
A valid gruntfile could not be found

### ISSUE THREAD

**Issue by SamDrummond** [Esri/attachment-viewer#28]
On a windows 10 machine using visual studio code with powershell. I'm getting the following error when running "npm start".

![image](https://user-images.githubusercontent.com/4656969/78735654-676a4480-799f-11ea-9b0e-50a5d424a4d1.png)

Prior to this, I have updated powershells execution policy to enable remotely signed scripts.

Is the gruntfile missing from the repo?

**Comment by rslibed** [comment]
@SamDrummond It looks like Gruntfile.js was listed in .gitignore. The file has been installed.

Feel free to re-open if you still run into issues.
